Feature: Chart Display # features/chart_display.feature:1

  Scenario: View data in a chart format                         # features/chart_display.feature:3
    Given the user is logged in                                 # features/steps/chart_display_steps.py:5
      Traceback (most recent call last):
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\chart_display_steps.py", line 7, in step_impl
          login_page = LoginPage(context.driver)
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\runner.py", line 321, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When the user clicks on the "Compare Expenses" button       # None
    And the user clicks on the "Show data for next year" button # None
    And the user clicks on the "Compare Expenses" button        # None
    And the user clicks on the "Show data for next year" button # None
    And the user clicks on the "Show expenses chart" button     # None
    Then the expenses chart should be displayed                 # None

Feature: Compare Expenses functionality # features/compare_expenses.feature:1

  Scenario: User can compare expenses for different periods of time         # features/compare_expenses.feature:3
    Given I am on the login page                                            # features/steps/login_steps.py:7
    When I enter valid credentials                                          # features/steps/login_steps.py:13
    And I am on the expenses page                                           # features/steps/compare_expenses_steps.py:12
      Traceback (most recent call last):
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\compare_expenses_steps.py", line 15, in step_impl
          assert expenses_page.is_expenses_page_displayed()
      AssertionError

    And I click the "Compare Expenses" button                               # None
    And I select the "2019" and "2020" options                              # None
    And I click the "Show data" button                                      # None
    Then I should see a chart comparing the expenses for the selected years # None

Feature: Dynamic Content # features/dynamic_content.feature:1
  As a user
  I want to see dynamic ads on the web page
  So that I can view different ads every time I refresh the page
  Scenario: Dynamic ads are displayed correctly         # features/dynamic_content.feature:6
    Given I am on the expenses page                     # features/steps/dynamic_content_steps.py:4
      Traceback (most recent call last):
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\dynamic_content_steps.py", line 6, in step_impl
          context.expenses_page = ExpensesPage(context.driver)
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\runner.py", line 321, in __getattr__
          raise AttributeError(msg)
      AttributeError: 'Context' object has no attribute 'driver'

    When I refresh the page                             # None
    Then I should see different dynamic ads on the page # None

Feature: Login functionality # features/login.feature:1
  As a user
  I want to be able to login to the web application
  So that I can access the protected resources
  Scenario: Successful login                     # features/login.feature:6
    Given I am on the login page                 # features/steps/login_steps.py:7
    When I enter valid credentials               # features/steps/login_steps.py:13
    And I click the login button                 # features/steps/login_steps.py:18
    Then I should be redirected to the main page # features/steps/login_steps.py:22
      Traceback (most recent call last):
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\model.py", line 1329, in run
          match.run(runner.context)
        File "C:\Users\homzi\AppData\Local\Programs\Python\Python310\lib\site-packages\behave\matchers.py", line 98, in run
          self.func(context, *args, **kwargs)
        File "features\steps\login_steps.py", line 26, in step_impl
          assert "ACME" in context.driver.current_url
      AssertionError


